# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 17:28
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Observaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('idAlerta', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateField()),
                ('Recordatorio', models.CharField(max_length=100)),
                ('Estatus', models.CharField(max_length=100)),
                ('Bloqueado', models.IntegerField(blank=True, default=0, editable=False)),
                ('Eliminado', models.IntegerField(blank=True, default=0, editable=False)),
                ('Usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Seguimientos',
            fields=[
                ('idSeguimiento', models.AutoField(primary_key=True, serialize=False)),
                ('FechaInicio', models.DateField()),
                ('FechaTermino', models.DateField()),
                ('Oficio', models.CharField(max_length=100)),
                ('Destinatario', models.CharField(max_length=100)),
                ('Fechaseguimiento', models.DateTimeField(blank=True, default=datetime.datetime(2017, 1, 30, 11, 28, 22, 754718))),
                ('Atendio', models.CharField(max_length=100)),
                ('Observacion', models.CharField(max_length=100)),
                ('Avance', models.CharField(max_length=100)),
                ('Estatus', models.CharField(max_length=100)),
                ('Bloqueado', models.IntegerField(blank=True, default=0, editable=False)),
                ('Eliminado', models.IntegerField(blank=True, default=0, editable=False)),
                ('Usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idObservacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Observaciones.Observaciones')),
            ],
        ),
        migrations.CreateModel(
            name='TipoSeguimiento',
            fields=[
                ('idTipoSeguimiento', models.AutoField(primary_key=True, serialize=False)),
                ('TipoSeguimiento', models.CharField(max_length=100)),
                ('Eliminado', models.IntegerField(blank=True, default=0, editable=False)),
            ],
        ),
        migrations.AddField(
            model_name='seguimientos',
            name='idTipoSeguimiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Seguimientos.TipoSeguimiento'),
        ),
        migrations.AddField(
            model_name='alerta',
            name='idSeguimiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Seguimientos.Seguimientos'),
        ),
    ]
