# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-02 16:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seguimientos', '0003_auto_20170202_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimientos',
            name='Fechaseguimiento',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 2, 2, 10, 38, 14, 200015)),
        ),
    ]
