# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-08 17:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seguimientos', '0005_auto_20170203_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='Usuario',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seguimientos',
            name='Fechaseguimiento',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 2, 8, 11, 10, 6, 150402)),
        ),
        migrations.AlterField(
            model_name='seguimientos',
            name='Usuario',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
