# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-13 18:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seguimientos', '0021_auto_20170213_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimientos',
            name='Fechaseguimiento',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 2, 13, 12, 19, 6, 102634)),
        ),
    ]
