# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 04:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seguimientos', '0026_auto_20170214_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimientos',
            name='Fechaseguimiento',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 2, 14, 4, 14, 55, 400448)),
        ),
    ]
