# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Auditoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observaciones',
            fields=[
                ('idObservaciones', models.AutoField(primary_key=True, serialize=False)),
                ('FechaInicio', models.DateField()),
                ('FechaTermino', models.DateField()),
                ('TituloObservacion', models.CharField(max_length=100)),
                ('Observacion', models.CharField(max_length=100)),
                ('Usuario', models.CharField(max_length=100)),
                ('Avance', models.CharField(max_length=100)),
                ('Estatus', models.CharField(max_length=100)),
                ('Bloqueado', models.IntegerField(blank=True, default=0, editable=False)),
                ('Eliminado', models.IntegerField(blank=True, default=0, editable=False)),
                ('idAuditoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Auditoria.Auditoria')),
            ],
        ),
    ]
