# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-02 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Observaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observaciones',
            name='Avance',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='observaciones',
            name='Estatus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Catalogos.Estatus'),
        ),
        migrations.AlterField(
            model_name='observaciones',
            name='FechaInicio',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='observaciones',
            name='FechaTermino',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='observaciones',
            name='Observacion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='observaciones',
            name='TituloObservacion',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
