# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-08 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Observaciones', '0003_auto_20170203_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observaciones',
            name='Estatus',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='Catalogos.Estatus'),
        ),
    ]
