# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-09 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Observaciones', '0004_auto_20170208_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observaciones',
            name='Avance',
        ),
        migrations.RemoveField(
            model_name='observaciones',
            name='FechaTermino',
        ),
        migrations.AlterField(
            model_name='observaciones',
            name='Observacion',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
