# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-09 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Observaciones', '0005_auto_20170209_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='observaciones',
            name='Plazo',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='observaciones',
            name='TipoObservacion',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
