# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-09 17:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dependencias', '0001_initial'),
        ('Observaciones', '0006_auto_20170209_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='observaciones',
            name='Dependencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dependencias.Dependencia'),
        ),
        migrations.AddField(
            model_name='observaciones',
            name='Enlace',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='observaciones',
            name='FechaActualizacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 2, 9, 11, 5, 30, 612728), editable=False),
        ),
        migrations.AddField(
            model_name='observaciones',
            name='FechaCreacion',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='observaciones',
            name='Observacion',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
