# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-09 17:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Observaciones', '0007_auto_20170209_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observaciones',
            name='FechaActualizacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 2, 9, 11, 13, 56, 231166), editable=False),
        ),
    ]
