# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-09 18:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dependencias', '0001_initial'),
        ('Observaciones', '0009_auto_20170209_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observaciones',
            name='Dependencia',
        ),
        migrations.AddField(
            model_name='observaciones',
            name='Dependencia',
            field=models.ManyToManyField(to='Dependencias.Dependencia'),
        ),
        migrations.AlterField(
            model_name='observaciones',
            name='FechaActualizacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 2, 9, 12, 11, 6, 918211), editable=False),
        ),
    ]
