# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-09 18:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Observaciones', '0011_auto_20170209_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='observaciones',
            name='Documento',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='observaciones',
            name='FechaActualizacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 2, 9, 12, 27, 7, 992644), editable=False),
        ),
    ]
