# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-09 18:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Observaciones', '0012_auto_20170209_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observaciones',
            name='FechaActualizacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 2, 9, 12, 29, 17, 832272), editable=False),
        ),
    ]
