# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-13 15:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Observaciones', '0015_auto_20170209_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observaciones',
            name='FechaActualizacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 2, 13, 9, 52, 19, 135318), editable=False),
        ),
    ]
