# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-13 18:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Observaciones', '0016_auto_20170213_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='observaciones',
            name='Resumen',
            field=models.FileField(blank=True, null=True, upload_to='archivos/'),
        ),
        migrations.AlterField(
            model_name='observaciones',
            name='FechaActualizacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 2, 13, 12, 19, 6, 100634), editable=False),
        ),
    ]
