# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 02:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Observaciones', '0017_auto_20170213_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observaciones',
            name='FechaActualizacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 2, 14, 2, 53, 38, 246868), editable=False),
        ),
    ]
