# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 03:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Observaciones', '0019_auto_20170214_0339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observaciones',
            name='Resumen',
        ),
        migrations.AlterField(
            model_name='observaciones',
            name='FechaActualizacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 2, 14, 3, 45, 41, 103779), editable=False),
        ),
    ]
