# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 03:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Observaciones', '0020_auto_20170214_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='observaciones',
            name='Resumen',
            field=models.FileField(blank=True, null=True, upload_to='archivos/'),
        ),
        migrations.AlterField(
            model_name='observaciones',
            name='FechaActualizacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 2, 14, 3, 51, 21, 416612), editable=False),
        ),
    ]
