# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAuditoria',
            fields=[
                ('idTipoAuditoria', models.AutoField(primary_key=True, serialize=False)),
                ('TipoAuditoria', models.CharField(max_length=100)),
                ('Eliminado', models.IntegerField(blank=True, default=0, editable=False)),
            ],
        ),
    ]
