# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TipoAuditoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('idAuditoria', models.AutoField(primary_key=True, serialize=False)),
                ('FechaInicioAuditoria', models.DateField()),
                ('FechaTerminoAuditoria', models.DateField()),
                ('NombreAuditoria', models.CharField(max_length=100)),
                ('Eliminado', models.IntegerField(blank=True, default=0, editable=False)),
                ('idTipoAuditoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TipoAuditoria.TipoAuditoria')),
            ],
        ),
    ]
