# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-09 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auditoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='FechaInicioAuditoria',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='FechaTerminoAuditoria',
            field=models.DateField(null=True),
        ),
    ]
